--- #YAML:1.0
 name: SMS-Send-AQL
 abstract: SMS::Send driver to send messages via AQL (www.aql.com)
 version: 0.03
 author:
   - David Precious <davidp@preshweb.co.uk>
 license: perl
 distribution_type: module
 requires:
   SMS::AQL: 0
   SMS::Send::Driver: 0
   perl: 5.005
 build_requires:
   Test: 0
 meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
 generated_by: hand

